### ISSUE TITLE
Add confirmation dialogue when deleting groups from admin side UI

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-custom-attributes#26] opened 2020-03-02 22:00 UTC
When an admin deletes a Custom Attributes group, there is no confirmation dialogue. Since this action cannot be undone, the user should be prompted to confirm the delete.

**Comment by hanzei** [comment] 2020-03-06 09:14
@DHaussermann I've made this into a HW

**Comment by nathanaelhoun** [comment] 2020-10-09 09:19
Hi! Is that a duplicate of #54?

**Comment by hanzei** [comment] 2020-10-09 10:14
Indeed. Thanks for the hint @nathanaelhoun :+1:

**Comment by hanzei** [comment] 2020-10-09 10:14
Duplicate of https://github.com/mattermost/mattermost-plugin-custom-attributes/issues/54

**Closed by hanzei** 2020-10-09 10:14 UTC
Labels: Duplicate
